services:
  nginx-part2:
    image: nginx:alpine
    container_name: bookstore-nginx-part2
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.part2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-part2
      - frontend-part2
    restart: unless-stopped

  backend-part2:
    image: hammadkhattak7/bookstore-backend:latest
    container_name: bookstore-backend-part2
    environment:
      - MONGODB_URI=mongodb+srv://bookstoreadmin:secretpwd@cluster0.l8rlybk.mongodb.net/bookstore?retryWrites=true&w=majority
      - PORT=4001
    restart: unless-stopped

  frontend-part2:
    image: hammadkhattak7/bookstore-frontend:latest
    container_name: bookstore-frontend-part2
    restart: unless-stopped
